"""rename address

Revision ID: 5ab40a0c842c
Revises: 2b9699342f00
Create Date: 2024-10-01 13:45:54.095227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab40a0c842c'
down_revision = '2b9699342f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
